const std = @import("std");

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});
    const external_vaxis = b.option(
        bool,
        "external_vaxis",
        "Consumer supplies the 'vaxis' import on the md module",
    ) orelse false;

    const update_expected = b.option(
        bool,
        "update-expected",
        "Regenerate expected test outputs",
    ) orelse false;

    const md_mod = b.addModule("md", .{
        .root_source_file = b.path("src/lib.zig"),
        .target = target,
        .optimize = optimize,
        .link_libc = true,
        .sanitize_c = .off,
    });
    addCDeps(b, md_mod);

    if (external_vaxis) return;
    const vaxis = b.lazyDependency("vaxis", .{
        .target = target,
        .optimize = optimize,
    }) orelse return;
    const vaxis_mod = vaxis.module("vaxis");
    md_mod.addImport("vaxis", vaxis_mod);

    // Executable (CLI + TUI pager): not part of the library surface
    const exe_mod = b.createModule(.{
        .root_source_file = b.path("src/main.zig"),
        .target = target,
        .optimize = optimize,
    });
    exe_mod.addImport("md", md_mod);
    exe_mod.addImport("vaxis", vaxis_mod);

    const exe = b.addExecutable(.{
        .name = "md",
        .root_module = exe_mod,
        // use llvm to avoid segfault on compilation with zig 0.16
        .use_llvm = true,
    });
    b.installArtifact(exe);

    const run_cmd = b.addRunArtifact(exe);
    run_cmd.step.dependOn(b.getInstallStep());
    if (b.args) |args| run_cmd.addArgs(args);
    const run_step = b.step("run", "Run md");
    run_step.dependOn(&run_cmd.step);

    // zig build fmt
    const fmt_paths: []const []const u8 = &.{ "src", "build.zig" };
    const fmt = b.addFmt(.{ .paths = fmt_paths });
    const fmt_step = b.step("fmt", "Format");
    fmt_step.dependOn(&fmt.step);

    // zig build fmt-check
    const fmt_check = b.addFmt(.{ .paths = fmt_paths, .check = true });
    const fmt_check_step = b.step("fmt-check", "Check formatting");
    fmt_check_step.dependOn(&fmt_check.step);

    const lib_tests = b.addTest(.{ .root_module = md_mod });
    const run_lib_tests = b.addRunArtifact(lib_tests);
    // Expected tests read tests/*.md relative to the project root.
    run_lib_tests.setCwd(b.path("."));
    // -Dupdate-expected regenerates tests/expected/ instead of comparing
    if (update_expected) run_lib_tests.setEnvironmentVariable("UPDATE_EXPECTED", "1");

    const exe_tests = b.addTest(.{ .root_module = exe_mod });
    const run_exe_tests = b.addRunArtifact(exe_tests);

    const test_step = b.step("test", "Run tests");
    test_step.dependOn(&run_lib_tests.step);
    test_step.dependOn(&run_exe_tests.step);
}

/// addCDeps compiles the C dependencies (md4c, tree-sitter runtime, grammars)
/// into `mod`.
fn addCDeps(b: *std.Build, mod: *std.Build.Module) void {
    const md4c = b.dependency("md4c", .{});
    mod.addIncludePath(md4c.path("src"));
    mod.addCSourceFiles(.{
        .root = md4c.path("src"),
        .files = &.{ "md4c.c", "entity.c" },
        .flags = &.{ "-std=c99", "-DMD4C_USE_UTF8" },
    });

    // tree-sitter runtime for code-block syntax highlighting
    mod.addIncludePath(b.path("vendor/tree-sitter/lib/include"));
    mod.addIncludePath(b.path("vendor/tree-sitter/lib/src"));
    mod.addCSourceFiles(.{
        .root = b.path("vendor/tree-sitter/lib/src"),
        .files = &.{"lib.c"},
        .flags = &.{ "-std=c11", "-D_DEFAULT_SOURCE" },
    });

    for (grammars) |g| addGrammar(b, mod, g);
}

/// Grammar SHAs are pinned in build.zig.zon and must stay with the
/// highlights queries regenerated by tools/regen-assets.sh
const Grammar = struct { name: []const u8, dep: ?[]const u8, scanner: bool };
const grammars = [_]Grammar{
    .{ .name = "json", .dep = "tree_sitter_json", .scanner = false },
    .{ .name = "go", .dep = "tree_sitter_go", .scanner = false },
    .{ .name = "c", .dep = "tree_sitter_c", .scanner = false },
    .{ .name = "python", .dep = "tree_sitter_python", .scanner = true },
    .{ .name = "rust", .dep = "tree_sitter_rust", .scanner = true },
    .{ .name = "javascript", .dep = "tree_sitter_javascript", .scanner = true },
    .{ .name = "bash", .dep = "tree_sitter_bash", .scanner = true },
    .{ .name = "toml", .dep = "tree_sitter_toml", .scanner = true },
    .{ .name = "lua", .dep = "tree_sitter_lua", .scanner = true },
    .{ .name = "zig", .dep = null, .scanner = false },
};

/// addGrammar compiles a tree-sitter grammar
fn addGrammar(b: *std.Build, mod: *std.Build.Module, g: Grammar) void {
    const root: std.Build.LazyPath = if (g.dep) |d|
        b.dependency(d, .{}).path("src")
    else
        b.path(b.fmt("vendor/grammars/{s}", .{g.name}));
    mod.addCSourceFiles(.{
        .root = root,
        .files = &.{"parser.c"},
        .flags = &.{"-std=c11"},
    });
    if (g.scanner) {
        mod.addCSourceFiles(.{
            .root = root,
            .files = &.{"scanner.c"},
            .flags = &.{"-std=c11"},
        });
    }
}
