#!/bin/bash

set -euo pipefail

cd "$(dirname "$0")/.."

TS_VER=0.25.10
FONT_SHA=8e279d2d864e79128e96188a6b9526cfa3fbfef9

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

# curl $1 and output into $2
fetch() {
  if ! curl -fsSL "$1" -o "$2"; then
    echo "fetch failed: $1" >&2
    return 1
  fi
}

# from the $1 repo, we fetch the $3.scm file, for the $2 git sha
get_scm() { # repo sha lang
  local base="https://raw.githubusercontent.com/$1/$2"
  echo " fetching $3 sha ${2:0:12}"
  mkdir -p src/highlight/queries
  fetch "$base/queries/highlights.scm" "src/highlight/queries/$3.scm"
}


echo "==> get tree-sitter scm files, add them into src/highlight"
get_scm tree-sitter/tree-sitter-json          001c28d7a29832b06b0e831ec77845553c89b56d json
get_scm tree-sitter/tree-sitter-go            2346a3ab1bb3857b48b29d779a1ef9799a248cd7 go
get_scm tree-sitter/tree-sitter-c             b780e47fc780ddc8da13afa35a3f4ed5c157823d c
get_scm tree-sitter/tree-sitter-python        26855eabccb19c6abf499fbc5b8dc7cc9ab8bc64 python
get_scm tree-sitter/tree-sitter-rust          77a3747266f4d621d0757825e6b11edcbf991ca5 rust
get_scm tree-sitter/tree-sitter-javascript    58404d8cf191d69f2674a8fd507bd5776f46cb11 javascript
get_scm tree-sitter/tree-sitter-bash          a06c2e4415e9bc0346c6b86d401879ffb44058f7 bash
get_scm tree-sitter-grammars/tree-sitter-toml 64b56832c2cffe41758f28e05c756a3a98d16f41 toml
get_scm tree-sitter-grammars/tree-sitter-lua  10fe0054734eec83049514ea2e718b2a56acd0c9 lua
get_scm tree-sitter-grammars/tree-sitter-zig  6479aa13f32f701c383083d8b28360ebd682fb7d zig


echo "==> tree-sitter runtime v$TS_VER"
fetch "https://github.com/tree-sitter/tree-sitter/archive/refs/tags/v$TS_VER.tar.gz" "$tmp/ts.tar.gz"
tar -xzf "$tmp/ts.tar.gz" -C "$tmp"
rm -rf vendor/tree-sitter
mkdir -p vendor/tree-sitter/lib
cp -R "$tmp/tree-sitter-$TS_VER/lib/include" vendor/tree-sitter/lib/include
cp -R "$tmp/tree-sitter-$TS_VER/lib/src" vendor/tree-sitter/lib/src
cp "$tmp/tree-sitter-$TS_VER/LICENSE" vendor/tree-sitter/LICENSE


echo "==> zig grammar sources"
ZIG_SHA=6479aa13f32f701c383083d8b28360ebd682fb7d
zig_base="https://raw.githubusercontent.com/tree-sitter-grammars/tree-sitter-zig/$ZIG_SHA"
mkdir -p vendor/grammars/zig/tree_sitter
fetch "$zig_base/src/parser.c" vendor/grammars/zig/parser.c
fetch "$zig_base/src/tree_sitter/parser.h" vendor/grammars/zig/tree_sitter/parser.h
fetch "$zig_base/src/tree_sitter/alloc.h" vendor/grammars/zig/tree_sitter/alloc.h 2>/dev/null || true
fetch "$zig_base/src/tree_sitter/array.h" vendor/grammars/zig/tree_sitter/array.h 2>/dev/null || true
fetch "$zig_base/LICENSE" vendor/grammars/zig/LICENSE


echo "==> font8x8 sha ${FONT_SHA:0:12}"
mkdir -p src/image
font_h="$tmp/font8x8_basic.h"
fetch "https://raw.githubusercontent.com/dhepper/font8x8/$FONT_SHA/font8x8_basic.h" "$font_h"
{
  echo "//! Public-domain 8x8 bitmap font by Daniel Hepper"
  echo "//! generated by tools/regen-assets.sh"
  echo ""
  # keep comments from h source file, rename func and add '.' in value (zig syntax)
  sed -E -e '/^(\/\*\*| \*\*\/)$/d' \
         -e 's|^ \*|//|' \
         -e 's|char font8x8_basic\[128\]\[8\] = \{|pub const glyphs = [_][8]u8{|' \
         -e 's|^( +)\{|\1.{|' "$font_h"
} > src/image/font8x8.zig

echo "done"
